exports.newWord = {
	wordList:["ZACHARY TAYLOR","THOMAS JEFFERSON","BILL CLINTON","GERALD FORD","ULYSSES S GRANT","DWIGHT D EISENHOWER","JOHN TYLER","BARACK OBAMA","ABRAHAM LINCOLN","RICHARD NIXON"],
};